-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.abilities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ability_name character varying(255),
    technology_name character varying(255),
    resume_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    name character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    company_name character varying(255),
    is_confirmed boolean,
    phone_number character varying(255),
    web_site character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers_pending_approval
(
    id integer NOT NULL,
    company_name character varying(255),
    email character varying(255),
    is_confirmed boolean,
    password character varying(255),
    phone_number character varying(255),
    web_site character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.foreign_languages
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    language_name character varying(255),
    languagelevel integer NOT NULL,
    resume_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    position_name character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seeker_images
(
    id integer NOT NULL,
    uploaded_at date,
    url character varying(255),
    job_seeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    birth_year integer,
    first_name character varying(255),
    identity_number character varying(255),
    last_name character varying(255),
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.links
(
    id integer NOT NULL,
    github_link character varying(255),
    linkedin_link character varying(255),
    resume_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.posts
(
    id integer NOT NULL,
    description character varying(1000),
    last_apply_date timestamp without time zone,
    max_salary double precision NOT NULL,
    min_salary double precision NOT NULL,
    position_count integer NOT NULL,
    city_id integer,
    status integer,
    employer_id integer,
    release_date timestamp without time zone,
    way_of_working_id integer,
    job_position_id integer,
    working_time_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.resumes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(255),
    github_address character varying(255),
    linkedin_address character varying(255),
    job_seeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL,
    date_of_graduation timestamp without time zone,
    school_name character varying(255),
    section_name character varying(255),
    starting_date timestamp without time zone,
    resume_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnel_confirmations
(
    id integer NOT NULL,
    confirmed_date character varying(255),
    employer_id integer,
    system_personnel_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnels
(
    department_id character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(255),
    password character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.ways_of_working
(
    id integer NOT NULL,
    working character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.work_experiences
(
    id integer NOT NULL,
    date_of_start timestamp without time zone,
    departure_date timestamp without time zone,
    job_position character varying(255),
    work_place_name character varying(255),
    resume_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.working_times
(
    id integer NOT NULL,
    "time" character varying(255),
    PRIMARY KEY (id)
);

ALTER TABLE public.abilities
    ADD FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.foreign_languages
    ADD FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id)
    NOT VALID;


ALTER TABLE public.job_seeker_images
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.links
    ADD FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id)
    NOT VALID;


ALTER TABLE public.posts
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.posts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.posts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.resumes
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (id)
    NOT VALID;


ALTER TABLE public.schools
    ADD FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id)
    NOT VALID;


ALTER TABLE public.system_personnels
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id)
    NOT VALID;

END;